# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            孤狼晖
tagline:          '简简单单的技术博客'
description:      '美团网Windows Phone开发工程师。热爱技术，更热爱生活。相信技术的力量可以改变人们的生活'
url:              http://lanyon.getpoole.com
paginate:         5

author:
  name:           'Zack'
  url:            http://tianhonghui.github.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
