# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            孤狼晖
tagline:          '一个简单的技术博客'
description:      '热爱技术，更热爱生活'
url:              http://lanyon.getpoole.com
paginate:         5

author:
  name:           'Zack'
  url:            http://tianhonghui.github.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
